# Generated by Django 4.0.2 on 2022-02-20 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tables', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='m2m',
            field=models.ManyToManyField(related_name='book_related', related_query_name='book', to='tables.Product'),
        ),
        migrations.AddField(
            model_name='cupboard',
            name='m2m',
            field=models.ManyToManyField(related_name='cupboard_related', related_query_name='cupboard', to='tables.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ('book', 'cupboard')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
